### ISSUE TITLE
Wrong RSS feed

### ISSUE THREAD

**Issue by morgoth** [lukesarnacki/lukesarnacki.github.com#1]
Hi there.

I wanted to subscribe to your blog, but unfortunately it points to: http://feeds.feedburner.com/piotrsarnacki

``` html
<link type="application/atom+xml" title="Lukas Sarnacki" rel="alternate" href="http://feeds.feedburner.com/piotrsarnacki">
```

**Comment by lukesarnacki** [comment]
No nie wygłupiaj się man!

Co Ty do mnie po angielskiemu piszesz :)

Dzięki za info, chociaż ten blog jest zapomniany trochę, napisałem jedną notkę i nie mam czasu....
